package com.oxidb.jdbc;

import java.io.*;
import java.net.Socket;
import java.sql.*;
import java.util.*;
import java.util.concurrent.Executor;

/**
 * JDBC Connection to OxiDB via OxiWire binary protocol over TCP.
 */
public class OxiDbConnection implements Connection {

    private final Socket socket;
    private final OutputStream out;
    private final InputStream in;
    private boolean closed;
    private boolean autoCommit = true;

    OxiDbConnection(String host, int port) throws SQLException {
        try {
            this.socket = new Socket(host, port);
            this.socket.setTcpNoDelay(true);
            this.out = new BufferedOutputStream(socket.getOutputStream());
            this.in = new BufferedInputStream(socket.getInputStream());
        } catch (IOException e) {
            throw new SQLException("Failed to connect to OxiDB at " + host + ":" + port, e);
        }
    }

    synchronized OxiWireCodec.OxiWireResponse sendCommand(Map<String, Object> command) throws SQLException {
        checkClosed();
        try {
            byte[] payload = OxiWireCodec.encodeRequest(command);
            OxiWireCodec.writeFrame(out, payload);
            byte[] response = OxiWireCodec.readFrame(in);
            return OxiWireCodec.decodeResponse(response);
        } catch (IOException e) {
            throw new SQLException("Communication error with OxiDB", e);
        }
    }

    private void checkClosed() throws SQLException {
        if (closed) throw new SQLException("Connection is closed");
    }

    // ── JDBC Interface ────────────────────────────────────────

    @Override
    public Statement createStatement() throws SQLException {
        checkClosed();
        return new OxiDbStatement(this);
    }

    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException {
        return createStatement();
    }

    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        return createStatement();
    }

    @Override
    public PreparedStatement prepareStatement(String sql) throws SQLException {
        checkClosed();
        return new OxiDbPreparedStatement(this, sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
        return prepareStatement(sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        return prepareStatement(sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
        return prepareStatement(sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
        return prepareStatement(sql);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
        return prepareStatement(sql);
    }

    @Override
    public DatabaseMetaData getMetaData() throws SQLException {
        checkClosed();
        return new OxiDbDatabaseMetaData(this);
    }

    @Override
    public void close() throws SQLException {
        if (!closed) {
            closed = true;
            try {
                socket.close();
            } catch (IOException e) {
                throw new SQLException("Error closing connection", e);
            }
        }
    }

    @Override
    public boolean isClosed() { return closed; }

    @Override
    public void setAutoCommit(boolean autoCommit) { this.autoCommit = autoCommit; }

    @Override
    public boolean getAutoCommit() { return autoCommit; }

    @Override
    public void commit() throws SQLException { checkClosed(); }

    @Override
    public void rollback() throws SQLException { checkClosed(); }

    @Override
    public void setReadOnly(boolean readOnly) {}

    @Override
    public boolean isReadOnly() { return false; }

    @Override
    public void setCatalog(String catalog) {}

    @Override
    public String getCatalog() { return "oxidb"; }

    @Override
    public void setTransactionIsolation(int level) {}

    @Override
    public int getTransactionIsolation() { return Connection.TRANSACTION_READ_COMMITTED; }

    @Override
    public SQLWarning getWarnings() { return null; }

    @Override
    public void clearWarnings() {}

    @Override
    public Map<String, Class<?>> getTypeMap() { return Collections.emptyMap(); }

    @Override
    public void setTypeMap(Map<String, Class<?>> map) {}

    @Override
    public void setHoldability(int holdability) {}

    @Override
    public int getHoldability() { return ResultSet.HOLD_CURSORS_OVER_COMMIT; }

    @Override
    public Savepoint setSavepoint() throws SQLException { throw new SQLFeatureNotSupportedException(); }

    @Override
    public Savepoint setSavepoint(String name) throws SQLException { throw new SQLFeatureNotSupportedException(); }

    @Override
    public void rollback(Savepoint savepoint) throws SQLException { throw new SQLFeatureNotSupportedException(); }

    @Override
    public void releaseSavepoint(Savepoint savepoint) throws SQLException { throw new SQLFeatureNotSupportedException(); }

    @Override
    public CallableStatement prepareCall(String sql) throws SQLException { throw new SQLFeatureNotSupportedException(); }

    @Override
    public CallableStatement prepareCall(String sql, int a, int b) throws SQLException { throw new SQLFeatureNotSupportedException(); }

    @Override
    public CallableStatement prepareCall(String sql, int a, int b, int c) throws SQLException { throw new SQLFeatureNotSupportedException(); }

    @Override
    public String nativeSQL(String sql) { return sql; }

    @Override
    public boolean isValid(int timeout) throws SQLException {
        if (closed) return false;
        try {
            var resp = sendCommand(Map.of("cmd", "ping"));
            return resp.ok();
        } catch (Exception e) {
            return false;
        }
    }

    @Override
    public void setClientInfo(String name, String value) {}

    @Override
    public void setClientInfo(Properties properties) {}

    @Override
    public String getClientInfo(String name) { return null; }

    @Override
    public Properties getClientInfo() { return new Properties(); }

    @Override
    public Array createArrayOf(String typeName, Object[] elements) throws SQLException { throw new SQLFeatureNotSupportedException(); }

    @Override
    public Struct createStruct(String typeName, Object[] attributes) throws SQLException { throw new SQLFeatureNotSupportedException(); }

    @Override
    public void setSchema(String schema) {}

    @Override
    public String getSchema() { return null; }

    @Override
    public void abort(Executor executor) throws SQLException { close(); }

    @Override
    public void setNetworkTimeout(Executor executor, int milliseconds) {}

    @Override
    public int getNetworkTimeout() { return 0; }

    @Override
    public Clob createClob() throws SQLException { throw new SQLFeatureNotSupportedException(); }

    @Override
    public Blob createBlob() throws SQLException { throw new SQLFeatureNotSupportedException(); }

    @Override
    public NClob createNClob() throws SQLException { throw new SQLFeatureNotSupportedException(); }

    @Override
    public SQLXML createSQLXML() throws SQLException { throw new SQLFeatureNotSupportedException(); }

    @Override
    public boolean isWrapperFor(Class<?> iface) { return false; }

    @Override
    public <T> T unwrap(Class<T> iface) throws SQLException { throw new SQLException("Not a wrapper"); }
}
