//! TypeScript type generation for a project — the `supabase gen types` analog.
//!
//! Emits one `types.ts` describing both engines of a project database:
//! - **SQL tables**: exact types from the catalog (`SHOW TABLES` + `DESCRIBE`),
//!   nullability included.
//! - **Document collections**: inferred by sampling documents — a field's type
//!   is the union of what was seen; fields absent from some documents become
//!   optional. Inference is honest about its limits: it documents the sample
//!   size in the header.

use std::collections::BTreeMap;

use serde_json::{Value, json};

use crate::upstream::Upstream;

/// How many documents per collection the inference reads.
const SAMPLE: u64 = 50;

/// Generate the full `types.ts` source for `db_ref`.
pub fn generate(upstream: &Upstream, db_ref: &str, project_name: &str) -> Result<String, String> {
    let mut out = String::new();
    out.push_str(&format!(
        "// Generated by OxiBase for project \"{project_name}\" ({db_ref}).\n\
         // SQL tables come from the catalog (exact); collections are inferred\n\
         // from up to {SAMPLE} sampled documents each — regenerate after schema\n\
         // changes. Usage:\n\
         //   const oxibase = createClient<Database>(url, key, {{ ref }});\n\n"
    ));

    let mut table_names: Vec<(String, String)> = Vec::new(); // (name, interface)
    let mut collection_names: Vec<(String, String)> = Vec::new();

    // ── SQL tables (exact, from DESCRIBE) ───────────────────────────────
    if let Ok(results) = sql(upstream, db_ref, "SHOW TABLES") {
        for row in rows_of(results.first()) {
            let Some(table) = row.first().and_then(|v| v.as_str()) else {
                continue;
            };
            let Ok(desc) = sql(
                upstream,
                db_ref,
                &format!("DESCRIBE \"{}\"", table.replace('"', "\"\"")),
            ) else {
                continue;
            };
            let iface = interface_name(table);
            let mut body = String::new();
            for col in rows_of(desc.first()) {
                let (Some(name), Some(ty)) = (
                    col.first().and_then(|v| v.as_str()),
                    col.get(1).and_then(|v| v.as_str()),
                ) else {
                    continue;
                };
                let nullable = col.get(2).and_then(|v| v.as_bool()).unwrap_or(true);
                let ts = sql_type_to_ts(ty);
                body.push_str(&format!(
                    "  {}: {}{};\n",
                    prop(name),
                    ts,
                    if nullable { " | null" } else { "" }
                ));
            }
            out.push_str(&format!(
                "/** SQL table `{table}` */\nexport interface {iface} {{\n{body}}}\n\n"
            ));
            table_names.push((table.to_string(), iface));
        }
    }

    // ── Document collections (inferred from samples) ────────────────────
    let collections = upstream
        .list_collections_in(db_ref)
        .unwrap_or_default()
        .into_iter()
        .filter(|c| !c.starts_with('_'))
        .collect::<Vec<_>>();
    for col in collections {
        let docs = upstream
            .find_sorted_in(db_ref, &col, &json!({}), &json!({"_id": -1}), SAMPLE, 0)
            .unwrap_or_default();
        let iface = interface_name(&col);
        // field -> (set of ts types, seen-in-count)
        let mut fields: BTreeMap<String, (Vec<String>, usize)> = BTreeMap::new();
        for doc in &docs {
            let Some(obj) = doc.as_object() else { continue };
            for (k, v) in obj {
                if k == "_version" {
                    continue;
                }
                let ts = json_type_to_ts(v);
                let entry = fields.entry(k.clone()).or_insert_with(|| (Vec::new(), 0));
                if !entry.0.contains(&ts) {
                    entry.0.push(ts);
                }
                entry.1 += 1;
            }
        }
        let mut body = String::new();
        for (k, (types, seen)) in &fields {
            let optional = *seen < docs.len();
            let mut types = types.clone();
            types.sort();
            // `null` merges into the union tail for readability.
            body.push_str(&format!(
                "  {}{}: {};\n",
                prop(k),
                if optional { "?" } else { "" },
                types.join(" | ")
            ));
        }
        if docs.is_empty() {
            body.push_str("  [key: string]: unknown; // no documents sampled\n");
        }
        out.push_str(&format!(
            "/** Collection `{col}` (inferred from {} document{}) */\nexport interface {iface} {{\n{body}}}\n\n",
            docs.len(),
            if docs.len() == 1 { "" } else { "s" }
        ));
        collection_names.push((col.clone(), iface));
    }

    // ── Aggregate map ───────────────────────────────────────────────────
    out.push_str("export interface Database {\n");
    for (name, iface) in table_names.iter().chain(collection_names.iter()) {
        out.push_str(&format!("  {}: {};\n", prop(name), iface));
    }
    out.push_str("}\n");
    Ok(out)
}

/// Run a SQL statement, returning the per-statement results array.
fn sql(upstream: &Upstream, db_ref: &str, text: &str) -> Result<Vec<Value>, String> {
    upstream
        .raw_call(&json!({
            "engine": "sql",
            "cmd": "sql",
            "db": db_ref,
            "sql": text,
        }))
        .map(|d| d.as_array().cloned().unwrap_or_default())
}

fn rows_of(result: Option<&Value>) -> Vec<Vec<Value>> {
    result
        .and_then(|r| r.get("rows"))
        .and_then(|r| r.as_array())
        .map(|rows| rows.iter().filter_map(|r| r.as_array().cloned()).collect())
        .unwrap_or_default()
}

fn sql_type_to_ts(ty: &str) -> &'static str {
    let base = ty.split('(').next().unwrap_or(ty).to_ascii_uppercase();
    match base.as_str() {
        "INT" | "INTEGER" | "BIGINT" | "SMALLINT" | "TINYINT" | "DOUBLE" | "FLOAT" | "REAL"
        | "DECIMAL" | "NUMERIC" | "TIMESTAMP" | "DATETIME" => "number",
        "BOOL" | "BOOLEAN" => "boolean",
        // BLOB travels base64 on the JSON wire.
        _ => "string",
    }
}

fn json_type_to_ts(v: &Value) -> String {
    match v {
        Value::Null => "null".into(),
        Value::Bool(_) => "boolean".into(),
        Value::Number(_) => "number".into(),
        Value::String(_) => "string".into(),
        Value::Array(items) => {
            let mut inner: Vec<String> = items.iter().map(json_type_to_ts).collect();
            inner.sort();
            inner.dedup();
            match inner.len() {
                0 => "unknown[]".into(),
                1 => format!("{}[]", inner[0]),
                _ => format!("({})[]", inner.join(" | ")),
            }
        }
        Value::Object(_) => "Record<string, unknown>".into(),
    }
}

/// `user_orders` / `user-orders` → `UserOrders`.
fn interface_name(name: &str) -> String {
    let mut out = String::new();
    let mut upper = true;
    for c in name.chars() {
        if c == '_' || c == '-' || c == '.' {
            upper = true;
        } else if upper {
            out.extend(c.to_uppercase());
            upper = false;
        } else {
            out.push(c);
        }
    }
    if out.is_empty() {
        "Unnamed".into()
    } else {
        out
    }
}

/// A property name, quoted when it isn't a valid TS identifier.
fn prop(name: &str) -> String {
    let valid = !name.is_empty()
        && name.chars().enumerate().all(|(i, c)| {
            c == '_' || c == '$' || c.is_ascii_alphabetic() || (i > 0 && c.is_ascii_digit())
        });
    if valid {
        name.to_string()
    } else {
        format!("\"{}\"", name.replace('"', "\\\""))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn names_and_props() {
        assert_eq!(interface_name("user_orders"), "UserOrders");
        assert_eq!(interface_name("deneme"), "Deneme");
        assert_eq!(prop("ok_name"), "ok_name");
        assert_eq!(prop("weird-name"), "\"weird-name\"");
    }

    #[test]
    fn json_inference() {
        assert_eq!(json_type_to_ts(&json!([1, 2])), "number[]");
        assert_eq!(json_type_to_ts(&json!([1, "a"])), "(number | string)[]");
        assert_eq!(json_type_to_ts(&json!({"a": 1})), "Record<string, unknown>");
    }

    #[test]
    fn sql_types() {
        assert_eq!(sql_type_to_ts("VARCHAR(30)"), "string");
        assert_eq!(sql_type_to_ts("INT"), "number");
        assert_eq!(sql_type_to_ts("BOOL"), "boolean");
        assert_eq!(sql_type_to_ts("TIMESTAMP"), "number");
    }
}
